#!/usr/bin/env bash
# Example demonstrating attestor role usage across different anchor types

set -euo pipefail

echo "=== Attestor Role Usage Examples ==="
echo ""

# Example 1: Fiat On/Off-Ramp Roles
echo "1. Fiat On/Off-Ramp Configuration"
echo "   Roles: kyc-issuer, transfer-verifier, compliance-approver"
echo ""
echo "   KYC Issuer (kyc-provider):"
echo "   - Issues KYC verification attestations"
echo "   - Operation: kyc_verification"
echo "   - Required fields: user_id, kyc_status, verification_timestamp, kyc_level"
echo ""
echo "   Transfer Verifier (bank-integration):"
echo "   - Confirms bank wire transfers"
echo "   - Operations: fund_transfer, fund_refund"
echo "   - Required fields: transaction_id, amount, currency, timestamp"
echo ""
echo "   Compliance Approver (compliance-officer):"
echo "   - Manual review and approval"
echo "   - Operation: withdrawal_approval"
echo "   - Required fields: user_id, amount, destination_account, approval_timestamp"
echo ""

# Example 2: Remittance Anchor Roles
echo "2. Remittance Anchor Configuration"
echo "   Roles: identity-verifier, settlement-bank, corridor-manager, compliance-checker"
echo ""
echo "   Identity Verifier (identity-verifier):"
echo "   - Verifies sender and recipient identities"
echo "   - Operations: sender_verification, recipient_verification"
echo "   - Supports: passport, national_id, driver_license, biometric"
echo ""
echo "   Settlement Bank (correspondent-bank):"
echo "   - Manages settlement with correspondent banks"
echo "   - Operations: settlement_instruction, settlement_confirmation"
echo "   - Provides settlement references and timestamps"
echo ""
echo "   Corridor Manager (corridor-operator):"
echo "   - Optimizes remittance routing"
echo "   - Operation: corridor_routing"
echo "   - Selects routes based on cost, speed, and availability"
echo ""
echo "   Compliance Checker (aml-screening):"
echo "   - Automated AML/CFT screening"
echo "   - Operation: aml_screening"
echo "   - Screens against OFAC, EU, UN sanctions lists"
echo ""

# Example 3: Stablecoin Issuer Roles
echo "3. Stablecoin Issuer Configuration"
echo "   Roles: reserve-verifier, collateral-custodian, treasury-operator, risk-analyst"
echo ""
echo "   Reserve Verifier (reserve-auditor):"
echo "   - Audits reserve adequacy"
echo "   - Operation: reserve_attestation"
echo "   - Confirms reserves backing stablecoins in circulation"
echo ""
echo "   Collateral Custodian (collateral-manager):"
echo "   - Manages collateral deposits and liquidations"
echo "   - Operations: collateral_deposit, collateral_liquidation"
echo "   - Monitors collateral ratios and executes liquidations"
echo ""
echo "   Treasury Operator (treasury-manager):"
echo "   - Authorizes mint/burn operations"
echo "   - Operations: mint_authorization, burn_confirmation, redemption_processing"
echo "   - Manages stablecoin supply"
echo ""
echo "   Risk Analyst (risk-monitor):"
echo "   - Monitors risk parameters"
echo "   - Operations: risk_assessment, price_feed"
echo "   - Provides price feeds and risk scores"
echo ""

# Example 4: Role-Based Security Configuration
echo "4. Security Configuration by Role"
echo ""
echo "   Rate Limits:"
echo "   - kyc-provider: 100 req/min, 5000 req/hour"
echo "   - bank-integration: 50 req/min, 2000 req/hour"
echo "   - compliance-officer: 20 req/min, 500 req/hour"
echo ""
echo "   Multi-Signature Requirements:"
echo "   - mint operation: 2 signatures from treasury-manager"
echo "   - burn operation: 2 signatures from treasury-manager"
echo "   - reserve-proof: 1 signature from reserve-auditor"
echo ""

# Example 5: Validation
echo "5. Configuration Validation"
echo ""
echo "   Validating all example configurations..."
echo ""

if [ -f "./scripts/validate_all.sh" ]; then
    ./scripts/validate_all.sh
    echo "   ✓ All configurations validated successfully"
else
    echo "   Note: Run ./scripts/validate_all.sh to validate configurations"
fi

echo ""
echo "=== Role Documentation ==="
echo "For detailed role permissions and usage, see: docs/attestor-roles.md"
echo ""
echo "=== Example Configurations ==="
echo "- Fiat On/Off-Ramp: configs/fiat-on-off-ramp.json"
echo "- Remittance Anchor: configs/remittance-anchor.json"
echo "- Stablecoin Issuer: configs/stablecoin-issuer.json"
echo ""
